spring.application.name=backend

spring.data.mongodb.uri=${MONGODB_URI}

spring.data.mongodb.database=smart_traffic_db

spring.data.mongodb.auto-index-creation=true

logging.level.com.smarttraffic.backend=DEBUG

server.servlet.session.persistent=false