spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://Sunilrathore:Sunil_2004@cluster0.ewph4qe.mongodb.net/smart_traffic_db?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=smart_traffic_db

spring.data.mongodb.auto-index-creation=true